vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        album_image:
            uri_prefix: /images/albums
            upload_destination: '%kernel.project_dir%/public/images/albums'
